<?php

namespace Tests\Unit;

use Tests\TestCase;
use Tests\TestDataFaker;

class OrderTest extends TestCase
{
    private $faker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = new TestDataFaker();
    }

    /**
     * New Order API unit test.
     *
     * @return void
     */
    public function testNewOrderApi()
    {
        $this->json('POST', 'api/order/create', $this->faker->prepareNewOrderData(), ['Accept' => 'application/json'])->assertOk()->assertJsonStructure([
            'error',
            'success',
            'message',
            'data',
        ])->assertJson([
            'error'   => false,
            'success' => true,
            'message' => __('sticky.new_order_create_success'),
        ]);
    }

    /**
     * Update Order API unit test.
     *
     * @return void
     */
    public function testUpdateOrderApi()
    {
        $this->json('POST', 'api/order/update', $this->faker->prepareUpdateOrderData(), ['Accept' => 'application/json'])->assertOk()->assertJsonStructure([
            'error',
            'success',
            'message',
            'data',
        ])->assertJson([
            'error'   => false,
            'success' => true,
            'message' => __('sticky.update_order_success'),
        ]);
    }

    /**
     * View Order API unit test.
     *
     * @return void
     */
    public function testViewOrderAPI()
    {
        $this->json('POST', 'api/order/view', $this->faker->prepareViewOrderData(), ['Accept' => 'application/json'])->assertOk()->assertJsonStructure([
            'error',
            'success',
            'message',
            'data',
        ])->assertJson([
            'error'   => false,
            'success' => true,
            'message' => __('sticky.view_order_success'),
        ]);
    }
}
