<?php

namespace Tests\Unit;

use Illuminate\Support\Facades\Config;
use Tests\TestCase;
use Tests\TestDataFaker;

class ProspectTest extends TestCase
{
    private $faker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = new TestDataFaker();
    }
    /**
     * New Prospect API unit test.
     *
     * @return void
     */
    public function testNewProspectApi()
    {
        $this->json('POST', 'api/prospect/create', $this->faker->prepareNewProspectData(), ['Accept' => 'application/json'])->assertOk()->assertJsonStructure([
            'error',
            'success',
            'message',
            'data',
        ])->assertJson([
            'error'   => false,
            'success' => true,
            'message' => __('sticky.new_prospect_create_success'),
        ]);
    }

    /**
     * Update Prospect API unit test.
     *
     * @return void
     */
    public function testUpdateProspectApi()
    {
        $this->json('POST', 'api/prospect/update', $this->faker->prepareUpdateProspectData(), ['Accept' => 'application/json'])->assertOk()->assertJsonStructure([
            'error',
            'success',
            'message',
            'data',
        ])->assertJson([
            'error'   => false,
            'success' => true,
            'message' => __('sticky.update_prospect_success'),
        ]);
    }
}
