<?php

namespace Tests\Unit;

use Tests\TestCase;
use Tests\TestDataFaker;

class UpsellTest extends TestCase
{
    private $faker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = new TestDataFaker();
    }

    /**
     * New Upsell API unit test.
     *
     * @return void
     */
    public function testNewUpsellApi()
    {
        $this->json('POST', 'api/upsell/create', $this->faker->prepareNewUpsellData(), ['Accept' => 'application/json'])->assertOk()->assertJsonStructure([
            'error',
            'success',
            'message',
            'data',
        ])->assertJson([
            'error'   => false,
            'success' => true,
            'message' => __('sticky.new_upsell_create_success'),
        ]);
    }
}
